name: YourEnchant
main: me.Zacx.YE.Main.Core
version: 0.1
commands:
   testitem:
      description: TestItem.
      usage: /<command>
   enchant:
      description: TestItem.
      usage: /<command>
   socket:
      description: TestItem.
      usage: /<command>